### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by AivanK** [bradshjg/flask-githubapp#10]
I've got this error in ngrok when i install the app in Github. eg [https://imgur.com/a/Wnv8PXg](https://imgur.com/a/Wnv8PXg)
What can be the reason for this to be happening?

**Comment by bradshjg** [comment]
Were you able to get this working. What do your server logs show?

**Comment by AivanK** [comment]
Sorry for answering only know...
No @bradshjg, i couldn't, it says error with main now, will check the environment variables.
From what I've seen that's the only possible problem.

**Comment by bradshjg** [comment]
If you're still running into issues then pasting the traceback will potentially be helpful (or ideally providing a reproducible case).

**Comment by dato** [comment]
I had to enable logging:

```
logging.getLogger("flask_githubapp").addHandler(logging.StreamHandler())
```

Then I saw it was:

```
GitHub hook signature verification failed.
```

But I still haven't been able to discover why.

**Comment by AivanK** [comment]
> I had to enable logging:
> 
> ```
> logging.getLogger("flask_githubapp").addHandler(logging.StreamHandler())
> ```
> 
> Then I saw it was:
> 
> ```
> GitHub hook signature verification failed.
> ```

It actually worked...well i mean, i know the error.

It's the same as yours, did you manage to solve it?

**Comment by dato** [comment]
Yes. It was a problem with my webhook secret.

**Comment by AivanK** [comment]
May i know was the solution that you used?

**Comment by dato** [comment]
I don't really remember what my problem was. But you *must* set a secret.

**Comment by AivanK** [comment]
You mean the Webhook secret?
Thanks for your help.

**Comment by dato** [comment]
Yes. (Sorry, I won’t reply anymore. Good luck.)
