### ISSUE TITLE
No X-Hub-Signature header with GitHub Enterprise 

### ISSUE THREAD

**Issue by devlounge** [bradshjg/flask-githubapp#12]
Hi,

I wanted to use your cool library, however it fais on _verify_webhook as the X-Hub-Signature header is not present in the payload.

What could we do to remediate this, I would not want to clone / modify the code, ideally

**Comment by devlounge** [comment]
Hi, sorry, I discovered that it is set only when the github app has a secret set, no issue then.

**Comment by bradshjg** [comment]
Glad you got it sorted, would it have helped if the docs made it clear that a secret was required?
