### ISSUE TITLE
How to set environment variables

### ISSUE THREAD

**Issue by AivanK** [bradshjg/flask-githubapp#9]
Hello,
How can i setup the env variables in order to run the code that you present? I'm talking about the tree you mentioned: GITHUBAPP_ID, GITHUBAPP_KEY_PATH, and GITHUBAPP_SECRET.

Thanks in advance.

**Comment by feliperazeek** [comment]
why can't you just do?

```
export GITHUBAPP_KEY_PATH="<value>"
export GITHUBAPP_ID="<id>"
export GITHUBAPP_SECRET="<secret>"
```

**Comment by AivanK** [comment]
Yeah but i don't have any values associated with them, so i can't export anything.

**Comment by feliperazeek** [comment]
I created a new app [here](https://github.com/settings/apps/new), see [doc](https://developer.github.com/apps/building-github-apps/creating-a-github-app/).
